name: Android Debug APK CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle.lockfile') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Node dependencies
        run: yarn install

      - name: Install Android build deps
        working-directory: android
        run: ./gradlew dependencies

      - name: Build debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Get build date
        id: vars
        run: echo "BUILD_DATE=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Rename APK with build date
        run: |
          mv android/app/build/outputs/apk/debug/app-debug.apk android/app/build/outputs/apk/debug/app-debug-$BUILD_DATE.apk

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-$BUILD_DATE
          path: android/app/build/outputs/apk/debug/app-debug-$BUILD_DATE.apk

